blank_issues_enabled: true
contact_links:
  - name: Questions and discussion
    url: https://github.com/withkarann/aifoxx/discussions
    about: For questions, ideas, and general discussion, please use Discussions.
